---
name: WWW-BashOrg
version: 0.0101
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: simple module to obtain quotes from http://bash.org/
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::Entities: 3.57
  HTML::TokeParser::Simple: 3.15
  LWP::UserAgent: 5.829
build_requires:
  Test::More: 0
provides:
  WWW::BashOrg:
    file: lib/WWW/BashOrg.pm
    version: 0.0101
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
